# Generated by Django 5.0 on 2023-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/', verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
