# Generated by Django 5.0 on 2023-12-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.ImageField(default=1, max_length=64, upload_to='', verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='code',
            field=models.TextField(max_length=64, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.TextField(max_length=64, verbose_name='Изображение'),
        ),
    ]
