# Generated by Django 5.0 on 2023-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_services_price_alter_services_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
